### PR TITLE
new get_topology function - adds topology information to speaker info

### PR DESCRIPTION
**Pull request by phut**
Adds to the speaker info information regarding it's standing in the network (master/slave relationship to other speakers)

...the GIT push didn't do quite what I expected I seem to have managed to push all the 0-4 -> 0.5 changes along with the changes I intended

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Hey @phut 

This looks very nice. I tried it out and it worked just fine except for a single thing, see the comment below. Regarding the git stuff. If your new code is fairly localized then may it would be better to just copy it out into another file and make a new branch to try in. For the record:
git fetch upstream
git checkout remotes/upstream/master
git checkout -b new_branch_name
git commit ....
git push
and a pull request and you should be good to go.

About the code:
In preparation of getting the code into pep8 shape, it would be great if you restricted the doc string (and all other lines for that matter) to 80 characters (it also makes it easier to review online).

I think it may prove a little confusing that the content returned by get_speaker_info will change dependent of whether you have called get_topology. So I would suggest to make a separate variable for this information. Either one that is initialized empty and filled in as needed the same way as the speaker_info varaible or maybe just a local variable that is returned. If you do decide to do that I would sugges as with the other info methods to initialize the dictionary with empty strings for all fields, so that we will always return a dict with all the same keys.

Line 926: I would suggest to break it out into two lines. It is generally not suggested to use : to get several statements on one line. Also no space here: len( self.speaker_info
and here in line 927: .count( ',')

Line 923. The name is set by the user and therefore can be anything, so it should be encoded as utf-8.

Keep up the nice work.
Regards Kenneth

**Comment by phut** [comment]
Well, that's 5 hrs of my life fighting with GIT that I'll never get back...

**Comment by KennethNielsen** [comment]
I hope that is wasn't the list of command that I threw in here that messed stuff up. Look, if you are still having problems with it,and if we are in somewhat compatible timezones (CET, UTC+1), then lets meet in IRC and have a look at it.

**Comment by DPH** [comment]
Great work @phut and thank you @KennethNielsen for your good comments I am learning from them.
Tested code and it works fine.
@phut I too am fighting up the GIT learning curve, but it is a great tool and I am impressed with what it can do. Great video http://www.youtube.com/watch?v=ZDR433b0HJY over an hour but really gets you into GIT.

Re code - agree with @KennethNielsen should be separate from get_speaker_info to avoid confusion. 
The slave / master property is important as you should only send any AVTransport messages (e.g. PLAY, STOP etc)  to masters - if you send them to a slave it often removes them from the group they were in making them a master. Other commands (e.g. Volume, Mute) can be sent to any Zone Players (Slaves and Masters).

Keep up the good work, Cheers Daivd

**Comment by KennethNielsen** [comment]
This has been resubmitted in a new thread so I'm closing this one. Please re-open if this is not correct.

**Pull request closed without merging**
