### PR TITLE
Implemented get_queue, based on soffes ruby project

### PR DESCRIPTION
**Pull request by labero**
Added get_queue (this is heavily based on get_queue that is implemented by soffes (in Ruby).

### CODE REVIEW

**Comment by rahims** [comment]
Thanks so much for the updates! I'd like to merge in `get_queue`, but would suggest that the TKinter GUI be spun off as a separate project that you manage with SoCo referenced as a submodule (http://git-scm.com/book/en/Git-Tools-Submodules).

This allows me to focus on the low level features of SoCo and let's other developers focus on building cool things (like GUIs) on top of the core library. This would also allow you to create a community of developers around building a really cool Tcl/Tk Sonos controller which could greatly benefit the Linux Sonos community.

Just let me know what the Github project URL is and I'll link to it in `README.md` so that others can find it easily. Does that work for you?

**Comment by labero** [comment]
Sure no problems. I'll send you a new one.

**Comment by labero** [comment]
Apparently it's possible to change a pull request. :) I've removed the GUI from the fork and the pull request.

**Comment by rahims** [comment]
Whoops, looks like the pull request got confused. The request is for the submodule addition (commit 5f60a45) rather than `get_queue` (commit 3f494ab). Is it possible to flip it? Or maybe cancel the pull request and send a new one just for `get_queue`?

Also, I think the submodule should be the other way around, so that SoCo is a submodule of SoCo-Tk rather than the other way around. That way, there isn't a dependency on SoCo having to build SoCo-Tk.

**Pull request closed without merging**
