### PR TITLE
re-submit get_topology. New get_speaker_info

### PR DESCRIPTION
**Pull request by phut**
This contains(and hopefully is better executed) my previous pull request to add the get_topology (plus this incorporates feedbackfrom other contributors) plus a new implementation of get_speaker_info which uses the "proper" url and returns a richer set of properties.

### CODE REVIEW

**Comment by DPH** [comment]
Looks exciting @phut well done. Can't wait to try but out until Friday. 
Cheers David

**Comment by DPH** [comment]
This is good and works for me. 
The new get_topology is great.
New version of get_speaker_info makes much more sense and provides more information.

One minor thing to change is the UID is returned as uuid:RINCON_000E5859E48601400 need to remove the 'uuid:'
suggestion: change line 754 to: 
           self.speaker_info['uid'] = tree.findtext('.//UDN').split(':')[1]

Two additions I think would be useful are to add the Sonos Model, and the icon url. Sugest add the following after line 754:
            self.speaker_info['icon_url'] = tree.findtext('.//device//iconList//url')
            self.speaker_info['sonos_model'] = tree.findtext('.//device//modelNumber')

One question is what people would use the capabilities for. I assuem all Sonos devices have the same?

Great work
Cheers David

NB assume we complete this Pull Request here rather than move it to the new site?

**Comment by phut** [comment]
They are mostly similar, but not all the same, which is why you should really interrogate this list before going on to interrogate all of the lists that it points to - the pertinent example here being the "line in" service which only exists on some devices. I'm also guessing that this will be a much more reliable way of distinguishing bridges and docks and also anything else on your network which answers the discovery request. I don't have a bridge to try with but my guess its it would show up as a zone player device but not as a renderer or a server. 

further, I am kind of hoping that this can be built upon so that put parsing the full service tree, we can get a definitive list of all the endpoints and functions at each. which will beat trying to guess them all with wireshark.

You are right about the uid, I missed that.

The icon is a bit more complicated. what you will get from here is a picture of the device itself. if you want the 'room' icons, they are in the next level down under one of the services, so will need to send out another request. I stopped at that point because I realized I was getting into a whole new level of upnp discovery, which may have to wait a while

**Comment by KennethNielsen** [comment]
Hallo @phut 

I just tried and it works great and it looks like a significant improvement. A few comments
When I ask for the capabilities in get_speak_info I get a list, that contains a dictionary with two elements, with keys 'device' and 'service'. How about turning the content of capabilities into a dictionary where they keys are the device names 'ZonePlayer', 'MediaServer' and 'MediaRenderer' and the content of each on is a dictionary with just the one element service which contains the same list as now. If you do it that way I will be able index my way directly down to the information I need and I can get the list of devices by the keys() method.

Line 12: About the imports. I think that unless there is a good reason for it, it is better to restrict the number of imports from the same module. Since we have already imported xml.etree.cElementTree as XML, you can access the two elements your are importing as XML.fromstring and XML.ElementTree and since they are only used in a few locations, I don't think there is any reason add the extra elements to the name space.

General: Indentation. This is of course something that one has to learn at some point. Never ever ever ever ever ever ever ever ever ever vary the level of indentation :) While python _can_ work with varying levels of indentation, it is a mess when you work with editors that auto indents a specific amount. And the errors that arrive from this can be **quite** tricky to solve, so to quote a piece of python documentation: "_Thou shalt indent with four spaces. No more, no less. Four shall be the number of spaces thou shalt indent, and the number of thy indenting shall be four. Eight shalt thou not indent, nor either indent thou two, excepting that thou then proceed to four. Tabs are right out._"

You define 4 namespace variables, which are then used as indices and concatenations, but only used in about 5 other lines. I think there might be en easier way to some of those things.
E.g. in lines 725-729, you could replace that whole thing with:

```
for elem in tree.getiterator():
    elem.tag = elem.tag.replace('{urn:schemas-upnp-org:device-1-0}', '')
```

which besides from being shorter imho is easier to read because I have the string right where it is used.
In line 745 the string that you are replacing is shorter than the length of the variable name you are using for it and it requires me to go back to see what it is the dictionary key will be.
That being said, there are of course cases where it is clever to move a long string out into a variable, but I'm not sure it is the best thing here.

The rest of what you use the name space variables for are essentially for removing them from the beginning and end of other strings, by concatenating them and counting their length. I think this implementation might be a little more error prone and not so easy to read. One could do essentially the same with the replace function or if you like with a regular expression implementation. The following is a suggestion for a regular expression implementation (requires import re in the beginning of the method or file):

```
# Strip out namespace from tags
for elem in tree.getiterator():
    elem.tag = elem.tag.replace('{urn:schemas-upnp-org:device-1-0}', '')

device_search = r'urn:schemas-upnp-org:device:(.*):1'
service_search = r'urn:schemas-upnp-org:service:(.*):1'
capabilities = []
for node in tree.findall('.//device'):
    element =  node.findtext('.//deviceType')
    re_search = re.search(device_search, element)
    device = {'device': re_search.group(1)}
    services = []
    for node2 in node.findall('.//service'):
        element =  node2.findtext('.//serviceType')
        re_search = re.search(service_search, element)
        services.append(re_search.group(1))
    device['service'] = services 
    capabilities.append(device)
```

and the same thing with ordinary replace functions:

```
# Strip out namespace from tags
for elem in tree.getiterator():
    elem.tag = elem.tag.replace('{urn:schemas-upnp-org:device-1-0}', '')

capabilities = []
for node in tree.findall('.//device'):
    element =  node.findtext('.//deviceType')
    device_name = element.replace('urn:schemas-upnp-org:device:', '')\
                  .replace(':1', '')
    device = {'device': device_name}
    services = []
    for node2 in node.findall('.//service'):
        element =  node2.findtext('.//serviceType')
        service_name = element.\
                       replace('urn:schemas-upnp-org:service:', '')\
                       .replace(':1', '')
        services.append(service_name)
    device['service'] = services 
    capabilities.append(device)
```

These are just suggestions and you should just feel free to reject it if you don't think it is better.

Besides from that there are a few commented out print statements that should probably be removed before merge.

In line 750 you use an "if variable" syntax. In general I almost always think that it is better to write it out so that we can see what it is that we get that we can't use. So I think the find text returns None if it does not find anything. This means that you could write

```
if name is not None:
```

and communicate that information to the reader.

Anyway, sorry about the rather length post. I hope you can use some of it.
Very nice work.
Regards Kenneth

**Comment by KennethNielsen** [comment]
Ahh. I forgot to look at the get_topology method, which I think is going to be very useful.

It is customary to mention the variable types in the doc string. Now of course, the return type is a dictionary and you do mention that, but since you go in and describe the content of that dictionary, you might as well mention their types as well. In most cases it will not become much longer.

Line 955. The default assignment. We haven't actually discussed what is the appropriate default value for all the different information that we get, but in most of the other methods we use an empty string as the default value for something that is supposed to return a string (whether that is "the right way" to do it is of course debatable), so maybe it will make sense to keep it that way. This of course does not apply for the is_master which is a Boolean, for which the default unassigned value should be None.
Another thing is that you mention in the docstring that if an error occurs the dictionary will be empty, but that is not strictly speaking the case. All or some of its elements will be None.

The default value also forms an issue in line 968. It seems that what you mean by "no group name" is that we actually get an empty string back, because len() will fail on None.

Nice work.

**Comment by DPH** [comment]
@phut I would be keen to get your code transferred to the new SoCo/SoCo and then pulled. It seems to have fallen through the cracks with the transfer to the new home for this code. 

On SoCo/SoCo @daubman has proposed a get_topology using xml - I feel the uPnP call in yours is better. 

Do you have the time to transfer it across and get the discussion going?

Cheers David

**Comment by phut** [comment]
I did not know we had moved!
Agree we should use the upnp calls throughout, don't know if I will have
time to do it ay time soon though. Quite happy for someone else to submit
it to the new repository it's self contained

**Comment by KennethNielsen** [comment]
I'm going to assume that this will be resubmitted at the new location if we are to include and I will then close the pull request here.

**Pull request closed without merging**
