### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by stefankoegl**
I've created a very basic [Sphinx](http://sphinx-doc.org/)-based documentation, located in the doc subdirectory.

To generate the output files, cd into the doc directory and run "make html". "make" without a target gives you a list of available formats (such as epub, latex, pdf, man pages, etc).

If somebody is interested in extending the documentation, have a look at [Quick reStructuredText](http://docutils.sourceforge.net/docs/user/rst/quickref.html) and [Sphinx documentation contents](http://sphinx-doc.org/contents.html).

Once the pull request is accepted, I can set up the project on [Read the Docs](https://readthedocs.org/) so that the documentation is automatically published online.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
I just tested it and it seems like an awesome base for some documentation.

Only thing to note is that we should probably mention the dependence on "sphinx" somewhere for generating the doc.

**Comment by stefankoegl** [comment]
I didn't want to add sphinx to requirements.txt as its not a runtime dependency. I could add a requirements-doc.txt instead. What do you think?

**Comment by KennethNielsen** [comment]
Yeah, I agree with you. The only thing I wanted was for the information to be there somewhere.

**Comment by DPH** [comment]
Looks interesting. Need to include a bit about how to use it - I have never used sphinx and I'm an sure there will be others like me. Fully support documentation as the project grows.
Cheers Daivd

**Comment by rahims** [comment]
Good work, Stefan! I'll read up a bit about Sphinx & reStructuredText (I've been meaning to anyway) and then add some docs as well.

**Comment by stefankoegl** [comment]
I've now set up the project on Read the Docs. The URLs are http://soco.readthedocs.org/ and http://soco.rtfd.org/. The project is now set up for rahims/SoCo, but I'll update it one #34 is done.

Please let me know if I should add anyone as maintainer at readthedocs.org.

@rahims Can you please enable the "Read the Docs" commit hook for the repository, so that the docs are automatically updated on every commit? I don't have admin permissions to do that.

**Comment by DPH** [comment]
This is great - very readable. Assume it is generated from the comments in SoCo, so providing we keep those up to date the documentation will be up to date. 

Cheers David

**Comment by stefankoegl** [comment]
Yes, at least partially. The [module documentation](http://soco.readthedocs.org/en/latest/soco-mod.html#module-soco) is auto-generated with the [Sphinx autodoc extension](http://sphinx-doc.org/ext/autodoc.html), but other content (such as the [mini-tutorial](http://soco.readthedocs.org/en/latest/tutorial.html)) can be freely edited.

**Comment by DPH** [comment]
Thanks - will read up on the links.
Cheers Daivd

**Comment by rahims** [comment]
Note: the ReadTheDocs service hook has been activated.

**Pull request merged**
